pref("extensions.xnotifier.startupDelay", 500);
pref("extensions.xnotifier.updateInterval", 10);
pref("extensions.xnotifier.maxConnections", 15);
pref("extensions.xnotifier.connections", 4);
pref("extensions.xnotifier.connectionDelay", 2000);
pref("extensions.xnotifier.openInTab",true);
pref("extensions.xnotifier.reuseTab",true);
pref("extensions.xnotifier.reloadTab",true);
pref("extensions.xnotifier.loadInBackground",false);
pref("extensions.xnotifier.resetCounter",false);
pref("extensions.xnotifier.checkOnStartup",true);
pref("extensions.xnotifier.autoLoginDefaultAccount",true);
pref("extensions.xnotifier.multiSession",true);
pref("extensions.xnotifier.yahoo.showCaptcha",true);
pref("extensions.xnotifier.showNotification",true);
pref("extensions.xnotifier.notificationDelay",4000);
pref("extensions.xnotifier.autoHideNotification",true);
pref("extensions.xnotifier.alertOrigin",0);
pref("extensions.xnotifier.alertTextStyle","");
pref("extensions.xnotifier.alertSound",true);
pref("extensions.xnotifier.customSound",false);
pref("extensions.xnotifier.soundUrl","");
pref("extensions.xnotifier.showStatusbarIcon",true);
pref("extensions.xnotifier.enableToolbar",true);
pref("extensions.xnotifier.showTabMenu",true);
pref("extensions.xnotifier.showBookmarkMenu",true);
pref("extensions.xnotifier.startupOpenXN",false);
pref("extensions.xnotifier.clearPasswdAlert",true);
pref("extensions.xnotifier.menuShowData",true);
pref("extensions.xnotifier.menuWindow",true);
pref("extensions.xnotifier.menuSidebar",true);
pref("extensions.xnotifier.inboxOnly",true);
pref("extensions.xnotifier.showFolders",true);
pref("extensions.xnotifier.dataColWidth",10);
pref("extensions.xnotifier.enabled",true);
pref("extensions.xnotifier.keepSession",false);
pref("extensions.xnotifier.keepSessionForNewTab",true);
pref("extensions.xnotifier.shortcut.sidebar.key","X");
pref("extensions.xnotifier.shortcut.sidebar.modifiers","accel,alt");
pref("extensions.xnotifier.showToolbarText",true);
pref("extensions.xnotifier.saveCookies",true);
pref("extensions.xnotifier.countTotal",0);
pref("extensions.xnotifier.activityIcon",0);
pref("extensions.xnotifier.iconLeftClick",0);
pref("extensions.xnotifier.debug",0);
pref("extensions.{ca4a1050-ba64-482e-8257-4e2c2fd26fa5}.description", "chrome://xnotifier/locale/overlay.properties");
pref("extensions.{ca4a1050-ba64-482e-8257-4e2c2fd26fa5}.creator", "chrome://xnotifier/locale/overlay.properties");
pref("extensions.{ca4a1050-ba64-482e-8257-4e2c2fd26fa5}.translator", "chrome://xnotifier/locale/overlay.properties");


